"use client";

import Breadcrumb from "@/components/pages/document/Breadcrumb";

const IntegrationGuidelines = () => {
  return (
    <div className="min-h-screen flex bg-[#121212] text-white">
      <div className="flex-1 p-8 max-w-3xl overflow-y-scroll">
        <Breadcrumb
          items={[
            { label: "Home", href: "/" },
            { label: "Integration Guidelines", href: "/integration-guidelines" },
          ]}
        />
        <h1 className="text-6xl font-bold mb-6 text-[#C0C0C0]">
          Integration Guidelines
        </h1>

        {/* System Integration Steps Section */}
        <section className="mb-12">
          <h2 className="text-4xl font-semibold mb-4 text-[#C0C0C0]">
            System Integration Steps
          </h2>
          <p className="mb-4 text-gray-300 text-left text-lg">
            We have upcoming apps for popular platforms like <strong>WordPress</strong>, <strong>Shopify</strong>, and <strong>Wix</strong>! These apps will allow seamless integration of client scores generated by our platform directly into their websites. 
          </p>
          <p className="mb-4 text-gray-300 text-left text-lg">
            With just a few clicks, clients will be able to display scores dynamically, ensuring real-time updates and enhanced user engagement.
          </p>
          <p className="text-gray-300 text-left text-lg">
            Similarly, we will be providing <strong>API support</strong> for all popular programming languages to facilitate effortless integration with custom platforms.
          </p>
        </section>

        {/* Code Snippets Section */}
        <section>
          <h2 className="text-4xl font-semibold mb-4 text-[#C0C0C0]">
            Code Snippets
          </h2>
          <p className="text-gray-300 text-left text-lg">
            <em>No Code Snippets available yet.</em>
          </p>
        </section>
      </div>
    </div>
  );
};

export default IntegrationGuidelines;
