"use client";

import Breadcrumb from "@/components/pages/document/Breadcrumb";
import PaginationButtons from "@/components/pages/document/PaginationButtons";
import TableOfContents from "@/components/pages/document/TableOfContents";

const IntegrationGuidelines = () => {
  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text).then(() => {
      alert("Code copied to clipboard!");
    });
    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  };
  const tableOfContents = [
    {
      title: "Integration Guidelines",
      links: [
        { label: "System Integration Steps", href: "#SystemIntegrationSteps" },
        { label: "Code Snippets", href: "#Code_Snippets" },
        // { label: "Intro to Development", href: "#" },
        // { label: "Wallets", href: "#" },
      ],
    },
    // {
    //   title: "Core Concepts",
    //   links: [
    //     { label: "Solana Account Model", href: "#" },
    //     { label: "Transactions and Instructions", href: "#" },
    //     { label: "Fees on Solana", href: "#" },
    //     { label: "Programs on Solana", href: "#" },
    //   ],
    // },
  ];
  return (
    <div className="min-h-screen max-w-screen flex bg-[#121212] text-white">
      <div className="flex-1 p-8 max-w-3xl overflow-y-scroll">
        <Breadcrumb
          items={[
            { label: "Home", href: "/" },
            {
              label: "Integration Guidelines",
              href: "/integration-guidelines",
            },
          ]}
        />
        <h1 className="text-6xl font-bold mb-6 text-[#C0C0C0]">
          Integration Guidelines
        </h1>

        {/* System Integration Steps Section */}
        <section className="pt-16" id="SystemIntegrationSteps">
          <h2 className="text-4xl font-semibold mb-4 text-[#C0C0C0]">
            System Integration Steps
          </h2>
          <p className="mb-4 text-gray-300 text-left text-lg">
            We have upcoming apps for popular platforms like{" "}
            <strong>WordPress</strong>, <strong>Shopify</strong>, and{" "}
            <strong>Wix</strong>! These apps will allow seamless integration of
            client scores generated by our platform directly into their
            websites.
          </p>
          <p className="mb-4 text-gray-300 text-left text-lg">
            With just a few clicks, clients will be able to display scores
            dynamically, ensuring real-time updates and enhanced user
            engagement.
          </p>
          <p className="text-gray-300 text-left text-lg">
            Similarly, we will be providing <strong>API support</strong> for all
            popular programming languages to facilitate effortless integration
            with custom platforms.
          </p>
        </section>

        {/* Code Snippets Section */}
        <section
          className="pt-16 max-w-screen overflow-x-scroll"
          id="Code_Snippets"
        >
          <h2 className="text-4xl font-semibold mb-4 text-[#C0C0C0]">
            Code Snippets
          </h2>
          <div className="text-gray-300 text-left text-lg">
            {/* <pre className="bg-[#1E1E1E] p-4 rounded text-sm text-[#C0C0C0] overflow-x-scroll relative scrollbar-hover">
              {`{ 
                "idea_stage": 5,
                "work_status": 3,
                "project_type": 3,
                "job_relation": 5,
                "investment_plan": 4,
                "work_experience": 4,
                "project_location": 1,
                "idea_description": "AI-powered fitness application that provides personalized workout routines based on user's fitness level and goals",
                "daily_hours": 4,
                "timeframe": 2
              }`}
              <button
                className="absolute top-2 right-2 bg-[#3B3B3B] text-white px-2 py-1 rounded text-xs"
                onClick={() =>
                  copyToClipboard(`{
                    "idea_stage": 5,
                    "work_status": 3,
                    "project_type": 3,
                    "job_relation": 5,
                    "investment_plan": 4,
                    "work_experience": 4,
                    "project_location": 1,
                    "idea_description": "AI-powered fitness application that provides personalized workout routines based on user's fitness level and goals",
                    "daily_hours": 4,
                    "timeframe": 2
                  }`)
                }
              >
                Copy Code
              </button>
            </pre> */}

            <h3 className="text-3xl text-left font-semibold mb-4 text-[#C0C0C0]">
              Response Format
            </h3>
            <h4 className="text-2xl font-semibold mb-2 text-[#C0C0C0]">
              Success Response (200 OK)
            </h4>
            {/* <pre className="bg-[#1E1E1E] p-4 rounded text-sm text-[#C0C0C0] overflow-x-auto relative">
              {`{
                "status": 200,
                "error": false,
                "message": "Success",
                "data": {
                  "resultText": "Detailed analysis and recommendations...",
                  "success_percentage": "75.23"
                }
              }`}
              <button
                className="absolute top-2 right-2 bg-[#3B3B3B] text-white px-2 py-1 rounded text-xs"
                onClick={() =>
                  copyToClipboard(`{
                    "status": 200,
                    "error": false,
                    "message": "Success",
                    "data": {
                      "resultText": "Detailed analysis and recommendations...",
                      "success_percentage": "75.23"
                    }
                  }`)
                }
              >
                Copy Code
              </button>
            </pre> */}

            <h4 className="text-xl md:text-2xl font-semibold mb-2 text-[#C0C0C0]">
              Validation Error Response (400)
            </h4>
            <pre className="bg-[#1E1E1E] p-4 rounded text-sm text-[#C0C0C0] overflow-x-scroll relative scrollbar-hover">
              {`{
  "status": 400,
  "error": true,
  "message": "Validation error message",
  "data": null
}`}
              <button
                className="absolute top-2 right-2 bg-[#3B3B3B] text-white px-2 py-1 rounded text-xs"
                onClick={() =>
                  copyToClipboard(`{
                  "status": 400,
                  "error": true,
                  "message": "Validation error message",
                  "data": null
                }`)
                }
              >
                Copy Code
              </button>
            </pre>

            <h4 className="text-2xl font-semibold mb-2 text-[#C0C0C0]">
              Server Error (500)
            </h4>
            <pre className="bg-[#1E1E1E] p-4 rounded text-sm text-[#C0C0C0] overflow-x-auto relative">
              {`{
                "status": 500,
                "error": true,
                "message": "An error occurred while processing your request",
                "data": null
              }`}
              <button
                className="absolute top-2 right-2 bg-[#3B3B3B] text-white px-2 py-1 rounded text-xs"
                onClick={() =>
                  copyToClipboard(`{
                    "status": 500,
                    "error": true,
                    "message": "An error occurred while processing your request",
                    "data": null
                  }`)
                }
              >
                Copy Code
              </button>
            </pre>
            <pre className="bg-[#1E1E1E] p-4 rounded text-sm text-[#C0C0C0] overflow-x-auto">
              {`<div>
  <img src="https://ideax.in/logo.png" alt="Logo" />
  <p>Validation Status: Valid</p>
  <p>Success Percentage: 85%</p>
  <div class="trustpilot-widget">...</div>
</div>`}
              <button
                className="absolute top-2 right-2 bg-[#3B3B3B] text-white px-2 py-1 rounded text-xs"
                onClick={() =>
                  copyToClipboard(`<div>
                    <img src="https://ideax.in/logo.png" alt="Logo" />
                    <p>Validation Status: Valid</p>
                    <p>Success Percentage: 85%</p>
                    <div class="trustpilot-widget">...</div>
                  </div>
                  `)
                }
              >
                Copy Code
              </button>
            </pre>
          </div>
        </section>
        <PaginationButtons
          previous={{ name: "Security Protocols", href: "/security-protocols" }}
          next={{ name: "Development Roadmap", href: "/development-roadmap" }}
        />
      </div>
      <TableOfContents data={tableOfContents} />
    </div>
  );
};

export default IntegrationGuidelines;
