"use client";

import Breadcrumb from "@/components/pages/document/Breadcrumb";
import PaginationButtons from "@/components/pages/document/PaginationButtons";
import TableOfContents from "@/components/pages/document/TableOfContents";

const DevelopmentRoadmap = () => {
    const tableOfContents = [
        {
          title: "Getting Started",
          links: [
            { label: "Quick Start", href: "#" },
            { label: "Installation", href: "#" },
            { label: "Intro to Development", href: "#" },
            { label: "Wallets", href: "#" },
          ],
        },
        {
          title: "Core Concepts",
          links: [
            { label: "Solana Account Model", href: "#" },
            { label: "Transactions and Instructions", href: "#" },
            { label: "Fees on Solana", href: "#" },
            { label: "Programs on Solana", href: "#" },
          ],
        },
      ];
  return (
    <div className="min-h-screen flex bg-[#121212] text-white">
      <div className="flex-1 p-8 max-w-3xl overflow-y-scroll">
        <Breadcrumb
          items={[
            { label: "Home", href: "/" },
            { label: "Development Roadmap", href: "/development-roadmap" },
          ]}
        />
        <h1 className="text-6xl font-bold mb-6 text-[#C0C0C0]">
          Development Roadmap & Support
        </h1>

        <section className="mb-12">
          {/* <h2 className="text-4xl font-semibold mb-4 text-[#C0C0C0]">
            Development Roadmap
          </h2> */}
          <p className=" text-left text-gray-300 text-lg mb-4">
            Our platform is fully operational, offering a seamless experience for our users. The website is live and equipped with robust functionality, including the <strong>&quot;Test Your Idea&quot;</strong> feature, which allows users to evaluate their business ideas and refine them for market readiness.
          </p>
          <p className="text-left text-gray-300 text-lg mb-4">
            Additionally, our <strong>powerful CRM feature set</strong> is designed to manage and analyze customer interactions effectively. To further enhance the user experience, we are developing dedicated apps for <strong>WordPress</strong>, <strong>Shopify</strong>, and <strong>Wix</strong>. These apps will empower users to:
          </p>
          <ul className="list-disc list-inside mb-4 text-gray-300">
            <li>Integrate scores generated by our platform to engage their audience.</li>
            <li>Customize the integration to align with their brand’s look and feel.</li>
          </ul>
          <p className="text-left text-gray-300 text-lg">
            Once these apps are launched, we’ll provide detailed step-by-step guides and comprehensive documentation to ensure a smooth integration process.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-4xl font-semibold mb-4 text-[#C0C0C0]">
            Future Features
          </h2>
          <p className="text-left text-gray-300 text-lg  mb-4">
            Expected Release: <strong>Second Quarter 2025</strong>
          </p>
          <p className="mb-4 text-left text-gray-300">Upcoming Features:</p>
          <ul className="list-disc list-inside text-gray-300">
            <li>Seamless payment processing for global freelancers and professionals.</li>
            <li>AI-powered Business Solution platform for enterprise clients.</li>
            <li>Marketplace for innovative startups.</li>
            <li>Launch of IDX on the BNB Smart Chain.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-4xl font-semibold mb-4 text-left text-gray-300">
            Support and Resources
          </h2>

          <div className="mb-6">
            <h3 className="text-2xl font-medium mb-2 text-left text-gray-300">
              Technical Support
            </h3>
            <p className="text-left text-gray-300 text-lg ">
              For technical assistance, please contact us at:
            </p>
            <ul className="list-none text-gray-300">
              <li>Email: <a href="mailto:support@ideax.in" className="text-blue-500">support@ideax.in</a></li>
              <li>Phone: <a href="tel:+1234567890" className="text-blue-500">+1 (234) 567-890</a></li>
              <li><a href="/support" className="text-blue-500">Submit a support ticket</a></li>
            </ul>
          </div>

          <div className="mb-6">
            <h3 className="text-2xl font-medium mb-2 text-left text-gray-300">
              Community Resources
            </h3>
            <ul className="list-disc list-inside">
              <li><a href="/forums" className="text-blue-500">Forums</a></li>
              <li><a href="/faq" className="text-blue-500">FAQs</a></li>
              <li><a href="/community" className="text-blue-500">User Communities</a></li>
            </ul>
          </div>

          <div>
            <h3 className="text-2xl font-medium mb-2 text-left text-gray-300">
              Legal and Licensing Information
            </h3>
            <p className="text-left text-gray-300 text-lg ">
              <strong>License Information:</strong> IDX is offered under the XYZ license, allowing commercial use with restrictions on redistribution.
            </p>
            <p className="text-left text-gray-300 text-lg ">
              <strong>Intellectual Property:</strong> All code, visuals, and content are proprietary to IDX Corporation unless otherwise stated.
            </p>
          </div>
        </section>
        <PaginationButtons previous={{ name: "Integration Guidelines", href: "/integration-guidelines" }} next={null}/>
      </div>
      <TableOfContents data={tableOfContents}/>
    </div>
  );
};

export default DevelopmentRoadmap;